### ISSUE TITLE
variable inside the key for css key:name pair

### ISSUE THREAD

**Issue by Jon-zachary** [Jon-zachary/project1GA#1]
@patrickandre I'm trying to assign different borders programmatically: so Instead of
```$(aBox).css({'border-left':`5px solid ${this.sideColor}`});``` 
I would like to have
```$(aBox).css({'border-VAR':`5px solid ${this.sideColor}`});```

I have tried using 'border -' + VAR and the same thing with template literals but the inside of the css call won't recognize it. All the things I googled assumed that I was trying to make the variable work inside the value which is fine but I can't find anything about the name. I could make an array with 4 key value pairs and randomly choose one but that feels a little hackey. Let me know if you have any ideas, thanks
Jon

**Comment by patrickandre** [comment]
We used brute force to just get this to work :). Feel free to close issue
